### ISSUE TITLE
Tower Specific Updrages

### ISSUE THREAD

**Issue by furknyavuz** [mfatihdurmus/tower-defense#3]
Arrow Tower Upgrades
- Flaming Arrow
- Poisoning Arrow

**Comment by cemozer** [comment]
@furkanyavuz91 yapıldı mı bu, yapılmadıysa ben alayım.

**Comment by furknyavuz** [comment]
@tyronjesper olabilir bunun üzerinde düşnüyorum ben de aklına bir şeyler gelirse söylersin bakarız
